### ISSUE TITLE
bad getWorkerUrl regex

### ISSUE THREAD

**Issue by wangkechun** [microsoft/monaco-editor-webpack-plugin#100]
ref: https://github.com/microsoft/monaco-editor-webpack-plugin/blob/v1.8.2/src/index.ts#L200
```
if publicPath = "//xxx.com/static"
/^(http:)|(https:)|(file:)/.test(publicPath) will false
```

@alexdima

**Comment by alexdima** [comment]
@wangkechun Would you be willing to create a PR to fix it?

**Comment by wangkechun** [comment]
done https://github.com/microsoft/monaco-editor-webpack-plugin/pull/101

**Comment by alexdima** [comment]
Thank you!
