### ISSUE TITLE
Load a language asynchronously

### ISSUE THREAD

**Issue by Menci** [microsoft/monaco-editor-webpack-plugin#104]
How can I load a language asynchronously with Webpack `import()` and use it in the editor?

**Comment by alexdima** [comment]
Here is an example, the `typescript` and `javascript` languages are loaded asynchronously using `import()` only when an editor with that particular language is instantiated -- https://github.com/microsoft/monaco-typescript/blob/61a0941817d7686dff2ac3b0e3b79681060c27f7/src/monaco.contribution.ts#L238-L247

**Comment by Menci** [comment]
Do you mean the TS/JS mode in moanco-editor is already loading asynchronously? What about other languages? That seems no help for me to load other languages asynchronously in my project.

**Comment by alexdima** [comment]
@Menci All of the languages that ship in the monaco editor load asynchronously if this webpack plugin is used.

You can check this by building/running the sample from https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin .

**Comment by Menci** [comment]
Nice! Thanks.
