### ISSUE TITLE
Failed to generate smaller editor bundle by selecting certain languages or editor features

### ISSUE THREAD

**Issue by VincentBel** [Microsoft/monaco-editor-webpack-plugin#11]
Even I set the `languages` and `features` options, the generated bundle will still include all languages & features:

```js
new MonacoWebpackPlugin({
  languages: ['java', 'json'],
  features: ['find'],
})
```

![image](https://user-images.githubusercontent.com/6076919/39994974-7c456bac-57ad-11e8-9136-2002949b8527.png)

---

### Possible Causes

webpack will use [the `module` field of `package.json`](https://github.com/Microsoft/monaco-editor/blob/8f3204478aa52ac7b16974b1a4691337e956ceae/package.json#L14
) as module entry:

```json
"module": "./esm/vs/editor/editor.main.js",
```

When we deal it with our `include.js` loader:

https://github.com/Microsoft/monaco-editor-webpack-plugin/blob/ff60cf8b84ad4895cddca612814b4228560ddfa6/loaders/include.js#L17

it will generate:

```js
module.exports = require('editor.main.js');
```

But the [`editor.main.js` file](https://unpkg.com/monaco-editor@0.13.0/esm/vs/editor/edcore.main.js) will include all languages & features.

So I think we should replace it with `editor.api.js`, something like:

```js
`module.exports = require(${loaderUtils.stringifyRequest(
  this,
  `!!${remainingRequest.replace('editor.main.js', 'editor.api.js')}`
)});`, 
```

**Comment by chengtie** [comment]
I have the same question as @VincentBel 

I thought if we chose less supported languages, the generated files would be smaller. But it seems that we always need to include the main `app.bundle.js` which is 2.1M.

Did I miss something?

**Comment by chengtie** [comment]
@VincentBel I tried your fork. But the generated `app.bundle.js`is still 2.1M; I still load it in the very beginning. Is it expected?

**Comment by VincentBel** [comment]
@chengtie I think the base size of `monaco-editor` maybe pretty large..

You can try to bundle the official sample here to test it:
https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-small

**Comment by alexandrudima** [comment]
The example at https://github.com/Microsoft/monaco-editor-webpack-plugin/tree/master/test now uses `import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';` to get only a subset of the editor packaged.

**Comment by roonyh** [comment]
@alexandrudima  So if we only want a subset of the languages and features and so want a smaller build in addition to this,
```javascript
new MonacoWebpackPlugin({
  languages: ['java', 'json'],
  features: ['find'],
})
```
we have to do `import 'monaco-editor/esm/vs/editor/editor.api'` instead of `import 'monaco-editor'` ?

**Comment by roonyh** [comment]
@VincentBel Cool! I am using webpack and this works for me for now. Thanks!

**Comment by rokkerruslan** [comment]
> @roonyh you can also add a [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) if you are using webpack:
> 
> ```js
> // webpack config
> 
> module.export = {
>   resolve: {
>     alias: {
>       'monaco-editor': 'monaco-editor/esm/vs/editor/editor.api.js'
>     }
>   }
> }
> ```
> 
> But in my opinion it should by handled by this plugin...

Regression after use it - https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodeldecorationoptions.html#hovermessage, `hoverMessage` does not woking now.
