### ISSUE TITLE
webpack build lots of chunks for monaco-editor

### ISSUE THREAD

**Issue by LucasGoodman** [microsoft/monaco-editor-webpack-plugin#114]
I use monaco-editor in the project created by vue-cli3.  
After the project was built, a lot of bundles were generated.
How can I make them load into one or a few js file?

`Editore.vue`
```
import * as monaco from 'monaco-editor';
monaco.editor.create(this.$refs.container, {
    model: newModel,
    theme: 'vs', 
    autoIndent: true, 
    scrollbar: {
        verticalScrollbarSize: 0,
        vertical: 'hidden'
    },
    minimap: {
        enabled: false
    },
    editorPosition: null,
    wordWrap: 'on',
    ...this.config
});
```

`vue.config.js`
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
configureWebpack: {
    plugins: [
        new MonacoWebpackPlugin({
            publicPath: resolve('dist/assets/js'),
            languages: ['sql', 'shell'],
            features: []
        })
    ]
}
```
**Before using the editor, the project packaging result is：**   
![before.png](https://i.loli.net/2020/05/12/mUG1xz32IuswClr.png)

**after,64 more files:**    
![after.png](https://i.loli.net/2020/05/12/f18RmL2jsarEHci.png)

**Comment by MarkKewley** [comment]
I'm experiencing the same issues as well, I thought specifying the `languages` option was supposed to reduce the bundle size but it seems to build all the languages regardless of what you specify. It is causing extra load times for initial page load.

**Comment by Beck-WuYu** [comment]
me too，Is it resolved?

**Comment by alexdima** [comment]
This is expected. The editor ships with 50+ language definitions and those languages will be loaded only when used (i.e. the `language` option when creating the editor or creating a text model).
