### ISSUE TITLE
Webpack builds all languages, even if the "language" option is set

### ISSUE THREAD

**Issue by iliakan** [microsoft/monaco-editor-webpack-plugin#117]
The config has:

```
  plugins: [
    new MonacoWebpackPlugin({
      languages: ['javascript', 'html', 'css'],
    })
  ]
```

In the `dist` folder, there are chunk files for every language, such as TCL, Go, etc.

They shouldn't be there, it seems.

**Comment by Xoto1162** [comment]
I have the same problem with languages and features.

I use this import :
```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
```

**Comment by erulabs** [comment]
I don't seem to have the issue with languages as far as I can tell, but I do with features:

Changing
``` features: ['clipboard'] ```
to
```
        features: [
          '!accessibilityHelp',
          '!bracketMatching',
          '!caretOperations',
          'clipboard',
          '!codeAction',
          '!codelens',
          '!colorDetector',
          '!comment',
          '!contextmenu',
          '!coreCommands',
```
etc
reduces the final bundle size of the monaco-editor package from `2.32 MB` to `424.96 KB`.

**Comment by iliakan** [comment]
Probably, the problem is fixed when I use `import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';` instead of `import * as monaco from `monaco'`.
