### ISSUE TITLE
Add support for webpack 5

### ISSUE THREAD

**Issue by otakustay** [microsoft/monaco-editor-webpack-plugin#124]
This plugin seems compatible with webpack 5, we can add `^5.0.0` to webpack's peer dependency description

**Comment by silverwind** [comment]
Webpack 5 is released, please update `peerDependencies` if module is compatible.

````
npm ERR! peer dep missing: webpack@^4.5.0, required by monaco-editor-webpack-plugin@2.0.0
````

**Comment by starpit** [comment]
Related issues (that only affect devDeps):

- `^` dependence on css-loader 4.x.x, whereas css-loader 5.0.1 has been released.
- ibid for style-loader 1.x.x, whereas 2.0.0 has been released

**Comment by zerocewl** [comment]
Any progress here or help needed?

**Comment by scottdickerson** [comment]
I also see this warning when using in Webpack5: 10% building(node:97848) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
