### ISSUE TITLE
All languages are bundled 

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/monaco-editor-webpack-plugin#125]
Hello,

We are using this library since a long time and didnot really paid attention to bundled results (as it really big anyway).
Just noticed today that all languages definition (`dev/vs/basic-languages/.*`) ends up in the prod bundle even whit the property `languages` specified.

Is it normal?
Thanks

**Comment by rhys-e** [comment]
Seeing the same behaviour, the `langauges` option doesn't seem to filter the bundled js files

**Comment by mattgodbolt** [comment]
Also seeing this, and it's leading to this hitting our Safari users: https://github.com/microsoft/monaco-editor/issues/2179

**Comment by mattgodbolt** [comment]
Ah! This is a result of calling `import * as monaco from 'monaco-editor'` or equivalent. The README says:

```
import * as monaco from 'monaco-editor'
// or import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
// if shipping only a subset of the features & languages is desired
```

And I had forgotten to do just that. Replacing the `import` with the `editor.api` one fixed inclusion for me!
