### ISSUE TITLE
Safari errors

### ISSUE THREAD

**Issue by sthielen** [microsoft/monaco-editor-webpack-plugin#129]
Hi, I'm having some issues with `2.0.0` of this plugin and `0.21.2` on Safari. Trying to instantiate Monaco throws an error: 

```
SyntaxError: Invalid regular expression: invalid group specifier name
(anonymous function) — npm.monaco-editor.12d5c85ea098be9f99ac.chunk.js:1
npm.sentry.3bad29c3529268800cfc.chunk.js:1:9733
```

Looks like it might be related to [this](https://github.com/microsoft/monaco-editor/issues/2179), but I haven't been able to fix it. Any ideas?

**Comment by mattgodbolt** [comment]
I concur it's linked to that issue, and is exarcebated by #125 as we can't exclude `dart` language.

**Comment by alexdima** [comment]
Duplicate of https://github.com/microsoft/monaco-editor/issues/2179
