### ISSUE TITLE
Error: Cannot find module 'vs/editor/contrib/anchorSelect/anchorSelect'

### ISSUE THREAD

**Issue by PeterlitsZo** [microsoft/monaco-editor-webpack-plugin#130]
the `monaco-editor-webpack-plugin/out/index.js` require it but cannot find it.

What need I do?

**Comment by Wobugaosuni** [comment]
me too. i have the same question

**Comment by Wobugaosuni** [comment]
> the `monaco-editor-webpack-plugin/out/index.js` require it but cannot find it.
> 
> What need I do?

i fixed the problem by degrading monaco-editor-webpack-plugin@1.8.2
checkout the versions:
![image](https://user-images.githubusercontent.com/19184250/100073045-f1581680-2e77-11eb-8e68-132d4dee1f59.png)

**Comment by tangdaohai** [comment]
please upgrade `monaco-editor`. ensure that monaco-editor-webpack-plugin and monaco-editor are the latest versions.
