### ISSUE TITLE
MonacoEnvironment.getWorker() doesn't fire for custom language

### ISSUE THREAD

**Issue by dkozar** [microsoft/monaco-editor-webpack-plugin#135]
Hi,

I implemented a custom language and the corresponding web worker.

I'm setting up the `getWorker()` and `getWorkerUrl()` callbacks during the app initialization:

```js
self.MonacoEnvironment = {
  getWorkerUrl: function (moduleId: string, label: string) {
    console.log('getWorkerUrl', moduleId, label)
  },
  getWorker: function (moduleId: string, label: string) {
      console.log('getWorker', moduleId, label)
  }
}
```

However, for some reason these callbacks are never executed **if the language is not one of the default ones provided by Monaco** (_javascript, typescript, sql_ etc.).

So, creating the editor like this doesn't trigger any callbacks:

```js
monaco.editor.create(divRef.current, {
    language: 'foo', // <--- custom language
    minimap: { enabled: false },
    value
});
```

This does trigger them:

```js
monaco.editor.create(divRef.current, {
    language: 'javascript', // <--- "out of the box" language
    minimap: { enabled: false },
    value
});
```
Here is the monaco-editor-webpack-plugin part of the config in _webpack.config_:

```js
new MonacoWebpackPlugin({
  languages: ['javascript'],
  customLanguages: [{
    label: 'foo',
    entry: undefined,
    worker: {
      id: 'foo-worker',
      entry: path.resolve(__dirname, '../node_modules/foo-library/dist/foo.worker.js')
    }
  }]
})
```

As you can see, my worker lives in another library (_node_modules/foo-library_).

As said, I'd primarily like to solve the issue of these callbacks not firing when I create Monaco editor. So I'm not concentrated on the implementation and the rest of the setup.

However, I'd also need some instructions on the `customLanguages` config. The documentation doesn't cover these in depth, so I don't understand what are the optional parameters above, and what each of them does. I created the separate issue for this: https://github.com/microsoft/monaco-editor-webpack-plugin/issues/136

Any help much appreciated! Thanks! 😄

**Comment by alexdima** [comment]
@dkozar If you have a custom language and you wish to start a web worker for it, you need to create a custom web worker by yourself.

You can simply call `new Worker()` by yourself and then pass messages to that worker and ask it to compute things for you. But if you need to work with text buffers, the monaco editor has a utility web worker to help you with the simple task of keeping a text buffer in sync on a web worker (called a mirror model). The builtin web worker utility can also help with very simple RPC-style calls where on the UI side you call a method on your web worker and the arguments and the return value is serialized.

The utility web worker can be created by calling `monaco.editor.createWebWorker`.  That is what all the smart builtin languages use. [Here](https://github.com/microsoft/monaco-typescript/blob/5a17ea5a5db63dc63a3c8741db1ce4ed71cb69ee/src/workerManager.ts#L62) you can see for example how `monaco-typescript` is using that API to create a web worker where it loads typescript. The same applies for `monaco-css`, `monaco-json` and `monaco-html`, they all need to have text buffer copies on which they operate and they end up using the same utility code.

**Comment by dkozar** [comment]
Thanks @alexdima!

I already have the worker code ready in a bundle, I'd just like to utilize the asynchronous loading of the worker on demand - i.e. if there are 2 languages available (_foo_ and _bar_), then I'd like to pull the _foo_ bundle only if the user uses _foo_ language.

I noticed that one could specify the bundle URL using `getWorkerUrl`, so I'd like to point to the bundle (which is exposed as a module by Webpack).

The problem is that `getWorkerUrl` won't fire if the language name isn't in [this language list](https://github.com/microsoft/monaco-editor-webpack-plugin/blob/6222e3fdb9bc391aace1131e53d0b62c42750b61/src/languages.ts).

So, without going into the worker implementation, I'm just wondering why this method doesn't fire if I'm creating the editor with a language "foo", but it fires if it is "javascript".

**Comment by alexdima** [comment]
@dkozar Please read again my previous response. **You need to create the web worker**. The monaco editor will not start web workers for your language.

**Comment by dkozar** [comment]
Thanks @alexdima! 🥇 

I finally managed to load the worker. 👍 

Please note that even before - I **was** actually creating the worker (using `createWebWorker`) method, but that didn't help.

What actually helped was **not using the `getWorker` and `getWorkerUrl` callbacks from `MonacoEnvironment` at all**.

For some reason I thought that these **must** be used in combination with `createWebWorker` because I saw this in another GitHub project implementing a custom language editor ([TodoLangEditor](https://github.com/amazzalel-habib/TodoLangEditor), [this](https://github.com/amazzalel-habib/TodoLangEditor/blob/master/src/todo-lang/setup.ts#L11) and [that](https://github.com/amazzalel-habib/TodoLangEditor/blob/master/src/todo-lang/WorkerManager.ts#L19) line).

So, this is enough to load the worker:

```js
monaco.languages.onLanguage('mylang', () => {
    this._worker = editor.createWebWorker<MyWorker>({
        moduleId: 'static/js/mylang.worker.chunk.js', // or 'static/js/mylang.worker.chunk'
    });
});
```

Notes:
1. The worker is served at: `http://localhost:3001/static/js/mylang.worker.chunk.js`.
2. The `onLanguage` subscription should be run BEFORE the editor is created, or else it never fires (with [ReactMonacoEditor](https://github.com/react-monaco-editor/react-monaco-editor) I call it from `editorWillMount`).

Another thing: the `createWebWorker` [example](https://github.com/microsoft/monaco-css/blob/ae46dfbebdf1e863c13e3ac4c8684399de34c929/src/workerManager.ts#L58) contains the following comment:

> // module that exports the create() method and returns a `CSSWorker` instance

However, for me this combination didn't work. I had to create a small worker script like [this one](https://github.com/microsoft/monaco-css/blob/master/src/css.worker.ts) (as you kindly pointed in https://github.com/microsoft/monaco-editor-webpack-plugin/issues/136) and this script creates the object instance using the new operator:

(Typescript code that compiles to `static/js/mylang.worker.chunk.js`:)

```ts
'use strict';

import * as edworker from 'monaco-editor/esm/vs/editor/editor.worker';
import { MyWorker } from 'mylang-worker';

self.onmessage = (message: any) => {
	console.log('MyWorker onmessage', message)
	edworker.initialize((context: monaco.worker.IWorkerContext, settings: My.Settings) => {
		console.log('initializing MyWorker')
		return new MyWorker(context)
	});
};

```

I wonder if the "other" notation with exposed `create()` method might be something obsolete (please correct me if I'm wrong)?

PS Hopefully this will help others struggling with the same issue!
