### ISSUE TITLE
Cannot find module 'vs/editor/contrib/rename/onTypeRename'

### ISSUE THREAD

**Issue by zhanghaoxu** [microsoft/monaco-editor-webpack-plugin#139]
Require stack:
- D:\project\netease\fe-nbaas\node_modules\monaco-editor-webpack-plugin\out\index.js
- D:\project\netease\fe-nbaas\config\plugin.config.js
- D:\project\netease\fe-nbaas\config\config.js
- D:\project\netease\fe-nbaas\node_modules\@umijs\core\lib\Config\Config.js
- D:\project\netease\fe-nbaas\node_modules\@umijs\core\lib\index.js
- D:\project\netease\fe-nbaas\node_modules\umi\lib\ServiceWithBuiltIn.js
- D:\project\netease\fe-nbaas\node_modules\umi\lib\forkedDev.js

today i find a new version 3.0 was released,but when i build old version "monaco-editor-webpack-plugin": "^2.0.0",i get this error,any solution？

**Comment by zhanghaoxu** [comment]
i tried v3.0.0 ,it worked!!

**Comment by majormark** [comment]
+1
