### ISSUE TITLE
Module not found : rename/onTypeRename

### ISSUE THREAD

**Issue by ZeBobo5** [microsoft/monaco-editor-webpack-plugin#140]
Error: Cannot find module 'vs/editor/contrib/rename/onTypeRename'

This module does not exists

**Comment by alexdima** [comment]
@ZeBobo5 Please see https://github.com/microsoft/monaco-editor-webpack-plugin/blob/master/README.md#version-matrix . Certain `monaco-editor-webpack-plugin` versions can load certain `monaco-editor` versions and they need to be upgraded together.
