### ISSUE TITLE
[3.0.0] peerDependencies range specifies only 0.22.x; README says 0.23 is supported

### ISSUE THREAD

**Issue by AviVahl** [microsoft/monaco-editor-webpack-plugin#142]
The `peerDependencies` range for `monaco-editor` should probably include `0.23.x`.
https://github.com/microsoft/monaco-editor-webpack-plugin/blob/main/package.json#L32

FYI @alexdima

**Comment by alexdima** [comment]
Thank you! Published `0.3.1`.
