### ISSUE TITLE
 Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by yazansalhi** [microsoft/monaco-editor-webpack-plugin#149]
plugins: [
    new MonacoWebpackPlugin({
      languages: ['javascript','typescript','css','html','json']
    }),
  ]
i found it at line 34 in AddWorkerEntryPointPlugin file

 const majorVersion = webpack.version.split('.')[0];
 
 webpack.version undefined
 
 its worked fine with old versions of monaco-editor-webpack-plugin
 
 "monaco-editor": "^0.24.0",
 "monaco-editor-webpack-plugin": "^3.1.0"
 "webpack": "^3.6.0",

**Comment by alexdima** [comment]
I'm sorry it doesn't seem to be working, but `webpack` 3.x is no longer supported. This is expressed in the [`peerDependencies`](https://github.com/microsoft/monaco-editor-webpack-plugin/blob/3517c361e6820bbd07eb5b73bcfdb77c10a74cc8/package.json#L31).

With so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

I'll close this issue, but if you have specific follow up questions, we'll try to help as good as we can given the limited resources that we have.

Thanks for your understanding!
