### ISSUE TITLE
typescriptServices.js compiled despite language not included in languages array

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/monaco-editor-webpack-plugin#15]
I noticed that with monaco-editor-webpack-plugin, the build took significantly longer than with the config I had before. I noticed this logline:
```
[BABEL] Note: The code generator has deoptimised the styling of "/buildkite/builds/buildkite-agent-dd84f899d-lss4w/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/web/node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js" as it exceeds the max of "500KB".
```
Which means the (huge) file `typescriptServices.js` (and probably all other languages too) was being piped through Babel and chunks generated from it, despite my config only specifying `json` as a language:

```ts
new MonacoWebpackPlugin({
            languages: ['json'],
            features: [
                'clipboard',
                'comment',
                'contextmenu',
                'coreCommands',
                'cursorUndo',
                'dnd',
                'find',
                'format',
                'hover',
                'inPlaceReplace',
                'iPadShowKeyboard',
                'linesOperations',
                'links',
                'parameterHints',
                'quickCommand',
                'quickFixCommands',
                'smartSelect',
                'suggest',
                'wordHighlighter',
                'wordOperations',
            ],
        }),
```
On Windows, I got this error:
```
ERROR in ./node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\felix\src\github.com\sourcegraph\sourcegraph\web\node_modules\monaco-editor\esm\vs\language\typescript\lib'
```
Again, despite typescript not being specified as a language.

I would expect the plugin to include only the files needed for the given languages and not compile all the languages into chunks that are never loaded.

**Comment by alexandrudima** [comment]
@felixfbecker I have changed the example in the `/test/` folder.

To get a subset of the editor, you would need to:

```js
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
```

instead of 

```js
import * as monaco from 'monaco-editor';
```

The reason is that the second form will end up import `monaco-editor/esm/vs/editor/editor.main` which will end up importing all the editor languages and features.

**Comment by cloverich** [comment]
Following the above advice addressed the issue for me. Wanted to drop a note to see if this section from monaco's [integrate-esm][1] instructions is related but maybe not accurate now?

```
  plugins: [
    // Ignore require() calls in vs/language/typescript/lib/typescriptServices.js
    new webpack.IgnorePlugin(
      /^((fs)|(path)|(os)|(crypto)|(source-map-support))$/,
      /vs(\/|\\)language(\/|\\)typescript(\/|\\)lib/
    )
  ]
```

Should it be changed / removed? (If you have suggestions, I can take a look and open a PR). It seems like you may be doing some related work per #9 

(Thanks for all the great work you've done on these projects!)

[1]: https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md#option-2-using-plain-webpack

**Comment by alexdima** [comment]
This is now removed, the IgnorePlugin is no longer used.
