### ISSUE TITLE
Outdated languages list

### ISSUE THREAD

**Issue by jonatanklosko** [microsoft/monaco-editor-webpack-plugin#150]
Elixir language definition has been added in https://github.com/microsoft/monaco-languages/pull/130 and made it to the 0.24.0 release. However, the generated `src/languages.ts` file doesn't include it.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/monaco-editor-webpack-plugin/commit/8589305d82069b1a2204a91a4d15a82381e3f96e

**Comment by jonatanklosko** [comment]
Thank you! :cat2:
