### ISSUE TITLE
Using with CRA crashes the compilation because of Webpack thread-loader

### ISSUE THREAD

**Issue by fguitton** [microsoft/monaco-editor-webpack-plugin#16]
Hello everybody !

While using `monaco-editor-webpack-plugin` with [`create-react-app`](https://github.com/facebook/create-react-app/blob/d0afe4b3b99b1b0b6ea5b72ccc50a6066c15aac0/packages/react-scripts/config/webpack.config.dev.js#L262) we can see the following error below.

This seems to be because of an incompatibility in the Webpack configuration with [`thread-loader`](https://github.com/webpack-contrib/thread-loader)

```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.main.js
Module build failed: Thread Loader (Worker 4)
Cannot read property 'userRequest' of undefined

    at Object.pitch (C:\Repos\project-ui\node_modules\monaco-editor-webpack-plugin\loaders\include.js:9:61)
 @ ./src/index.js 3:0-40
 @ multi ./node_modules/project-devutils/config/polyfills.js ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js
```

**Comment by ninjatron** [comment]
Similar problem with create-react-app. I get this error when I try to instantiate monaco editor webpack plugin in plugin definitions of webpack config:

$ react-scripts start
Failed to compile.

Cannot read property 'normalModuleFactory' of undefined

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by Fer0x** [comment]
Even with disabled thread-loader `yarn build` freezes and then crashes with lack of memory. The only working solution for me is to set up webpack config like this example: https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-small

**Comment by kandl** [comment]
For me, it's happening after upgrade react-create-app to v2.
I resolved it by removing those lines: https://github.com/Microsoft/monaco-editor-webpack-plugin/pull/41/commits/2698c974614c4c978ee56b0daacff3a8c1dec1aa

**Comment by Fer0x** [comment]
`thread-loader` has been removed in https://github.com/facebook/create-react-app/pull/5170
