### ISSUE TITLE
Add support for using webpack process:'mock'

### ISSUE THREAD

**Issue by wysisoft** [microsoft/monaco-editor-webpack-plugin#17]
Does the paste command not work in any way for anyone else? I'm using this plugin with vue cli and a very vanilla example with 0.13.1 or 0.13.0 and paste does not work in any way?

**Comment by alexandrudima** [comment]
Does Paste work for you at https://microsoft.github.io/monaco-editor/ ?

**Comment by alexandrudima** [comment]
How do you configure the plugin when you build the editor? Do you specify only a subset of features ?

**Comment by wysisoft** [comment]
find this method in the ESM directory of the monaco editor folder, inside
node_modules.

function StandaloneKeybindingService(contextKeyService, commandService,
telemetryService, notificationService, domNode) {
var _this = _super.call(this, contextKeyService, commandService,
telemetryService, notificationService) || this;
_this._cachedResolver = null;
_this._dynamicKeybindings = [];
_this.toDispose.push(dom.addDisposableListener(domNode,
dom.EventType.KEY_DOWN, function (e) {
var keyEvent = new StandardKeyboardEvent(e);
var shouldPreventDefault = _this._dispatch(keyEvent, keyEvent.target);
//start of my fix this allows ctrl-v to cause a paste
if(e.code == 'KeyV' && e.ctrlKey == true){
shouldPreventDefault = false;
}
//end of my fix
if (shouldPreventDefault) {
keyEvent.preventDefault();
}
}));
return _this;
}

**Comment by wysisoft** [comment]
Note that I ended up bailing on webpacking monaco - it creates a very large bundle, and it becomes really difficult to debug even when I put in debugger statements.

**Comment by ijse** [comment]
I find out it is relative with platform detecting.  It misunderstand that is running on native environment.

**Comment by ijse** [comment]
yes for now. in my circumstance it's ok. How do you solve the bundle size problem?

**Comment by ijse** [comment]
after travelling in source codes. I find the problem is relative with this setting in webpack.config.js: 
```
{ 
  node: {
    process: 'mock',
  },
}
``` 
These will add `process` in global, and `process.platform='browser'`. while `typeof process === 'object' && typeof process.platform === 'string'`, monaco will consider this is in Linux OS and is native environment which is wrong.

**Comment by wysisoft** [comment]
Good find on the true cause.
I moved away from webpack for this project. I am modifying monaco source code at certain points, and the bundle was too difficult to debug.

**Comment by ijse** [comment]
I debug by adding `debugger` in `node_modules/monaco-editor/esm/vs/*.js` file.

**Comment by wysisoft** [comment]
is it always caught? Chrome debugger would not catch my breakpoints for example, in the suggestion module

**Comment by alexdima** [comment]
This should work fine now.
