### ISSUE TITLE
worker files are bundled during webpack build but still referred to as /*.worker.js

### ISSUE THREAD

**Issue by CDoughty08** [Microsoft/monaco-editor-webpack-plugin#2]
The plugin builds everything fine, but when using with an ejected CRA application, bundles are built but the webworkers are still referring to their actual filename. My knowledge of webpack internals is pretty limited, so I imagine I am just doing something wrong.

The main.js file is still looking for a relative work path i.e. localhost:1234/editor.worker.js

I tweaked the 
`compiler.hooks.make.tapAsync('AddWorkerEntryPointPlugin', (compilation, callback) => {`
to
`compiler.plugin('make', (compilation, callback) => {`

so it would actually run on webpack 3.8

Any insight into what I can do to get this going?

EDIT: Did some further research, and managed to get a bit further, but now I get
`No dependency factory available for this dependency type: SingleEntryDependency`

I haven't found any references to this issue, I am assuming I still am doing something that doesn't work in webpack 3, but I am not entirely sure.

**Comment by mheavenor** [comment]
Hey @CDoughty08 ,

I ran into the same issue. I too am using CRA and was having trouble with webpack 3. I ended up just modifying AddWorkerEntryPointPlugin.js like so:

```
const singleEntry = require('webpack/lib/SingleEntryPlugin');
const loaderTarget = require('webpack/lib/LoaderTargetPlugin');
const webworker = require('webpack/lib/webworker/WebWorkerTemplatePlugin');

class AddWorkerEntryPointPlugin {
  constructor({
    id,
    entry,
    filename,
    chunkFilename = undefined,
    plugins = undefined,
  }) {
    this.options = { id, entry, filename, chunkFilename, plugins };
  }

  apply(compiler) {
    const { id, entry, filename, chunkFilename, plugins } = this.options;
    compiler.plugin('make', (compilation, callback) => {
      const outputOptions = {
        filename,
        chunkFilename,
        publicPath: compilation.outputOptions.publicPath,
        // HACK: globalObject is necessary to fix https://github.com/webpack/webpack/issues/6642
        globalObject: 'this',
      };
      const childCompiler = compilation.createChildCompiler(id, outputOptions, [
        new webworker(),
        new loaderTarget('webworker'),
        new singleEntry(compiler.context, entry, 'main'),
      ]);
      plugins.forEach((plugin) => plugin.apply(childCompiler));
      childCompiler.runAsChild(callback);
    });
  }
}

module.exports = AddWorkerEntryPointPlugin;
```

**Comment by internalfx** [comment]
I get this same error trying to use monaco-editor with nuxt.js
