### ISSUE TITLE
monaco-editor-webpack-plugin work with electron error

### ISSUE THREAD

**Issue by wenbinke** [microsoft/monaco-editor-webpack-plugin#24]
When I use `monaco-editor-webpack-plugin` in electron project, I got 2 errors. It takes me a few days to investigate, but still cannot figure it out.

First error is in the command line.
```sh
warning  in ./node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js
Critical dependency: the request of a dependency is an expression
```
![image](https://user-images.githubusercontent.com/482107/42734499-8837ad44-8877-11e8-928d-7cb00fa601d4.png)

Second error is in the "Developer Tools->Console"
```
errors.js?fdcc:58 Uncaught Error: Cannot find module 'vs/language/typescript/tsWorker'

Error: Cannot find module 'vs/language/typescript/tsWorker'
    at webpackEmptyContext (eval at ./node_modules/monaco-editor/esm/vs/editor/common/services sync recursive (
```
![image](https://user-images.githubusercontent.com/482107/42734494-64388058-8877-11e8-8820-1e215d0a9460.png)

You can reproduce the bug use the code in https://github.com/wenbinke/monaco-editor-electron.

```sh
yarn
yarn serve:electron
```

======================================================================
1. https://github.com/wenbinke/monaco-editor-electron/blob/master/vue.config.ts

```ts
import MonacoWebpackPlugin from 'monaco-editor-webpack-plugin';

export default {
  configureWebpack: {
    plugins: [
      new MonacoWebpackPlugin(),
    ],
  },
};
```
2. https://github.com/wenbinke/monaco-editor-electron/blob/master/src/views/Home.vue

```ts
import { Component, Vue } from "vue-property-decorator";
import * as monaco from "monaco-editor";

@Component
export default class Home extends Vue {
  public $refs!: {
    container: HTMLElement;
  }
  public mounted() {
    monaco.editor.create(this.$refs.container, {
      value: 'console.log("Hello, world")',
      language: "javascript"
    });
  }
}
```

**Comment by pboymt** [comment]
I have the same bug with Angular, but pure js is OK.

**Comment by wenbinke** [comment]
@alexandrudima Any plans for fixing this error?

**Comment by wenbinke** [comment]
It is buggy and less support. I already switched to codemirror.

**Comment by pboymt** [comment]
@wenbinke here [Here](https://github.com/superRaytin/react-monaco-editor/issues/134) is a method to solve this problem.

**Comment by wenbinke** [comment]
@pboymt, I tried this before. but no luck.

**Comment by pboymt** [comment]
@wenbinke I solve it, so I thought your problem might be a bug of Vue with TypeScript.

**Comment by marbemac** [comment]
For us, it was the webpack target. It should be set to one of the two electron options, such as:

```json
{
    "target": "electron-renderer"
}
```

**Comment by mengxiangyue** [comment]
```
{
        test: /^((?!\.global).)*\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]'
            }
          }
        ],
        exclude:[path.resolve(__dirname, '..', 'node_modules/monaco-editor')]
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
        include:[path.resolve(__dirname, '..', 'node_modules/monaco-editor')]
      },
```
you can use this. `exclude...`and `include`

**Comment by alexdima** [comment]
The OP has switched to code mirror, so closing this.
