### ISSUE TITLE
Using only JavaScript in ^0.14.2 has no Language Service

### ISSUE THREAD

**Issue by nikeee** [microsoft/monaco-editor-webpack-plugin#27]
I just updated to the latest version of `monaco-editor` and  `monaco-editor-webpack-plugin`:
```shell
$ npm ls | grep monaco
├── monaco-editor@0.14.2
├── monaco-editor-webpack-plugin@1.5.1
```

`webpack.config.js`:
```JavaScript
new MonacoWebpackPlugin({
    languages: ['javascript'],
}),
```
Usage of monaco:
```TypeScript
import * as monaco from 'monaco-editor'

monaco.editor.create(document.getElementById('container'), {
    value: 'console.log("Hello, world")\n',
    language: 'javascript',
});
```

I only want to edit JavaScript code. When running with the versions mentioned above, there seems to be no language service running validating the document or providing any kind of service (IntelliSense etc.).
Looking at the network requests, the front end is requesting `GET /undefined`, followed by an exception with the message `Error: Unexpected usage`.

I suspect that this is the language service that is missing and the regression might be introduced in f86321e0521832cfd22f03fa3c6f5eacc8546b1c (only guessing at this point).

If the plugin config is changed to include all language services (`new MonacoWebpackPlugin()`), it works and requests the TypeScript worker, as it should be. However, to reduce the bundle size, I only want the JS/TS service to be included (no CSS etc).

If TypeScript is added to the languages list:
```JavaScript
new MonacoWebpackPlugin({
    languages: ['javascript', 'typescript'],
})
```
Everything is also fine (this is the current workaround). It seems that somehow the information is lost that JS has the same LS as TS and is therefore not included in the bundle when only JS is included in the `languages` option.

**Comment by alexandrudima** [comment]
Sorry about that! The correct thing to do is to include both `javascript` and `typescript`!

The long story is that `typescript` and `javascript` have distinct colorizers, but share the same implementation for the language smarts. i.e. we have a `tsWorker` that services both `javascript` and `typescript`.

Before 0.14.x, the coloring of `typescript` and `javascript` was done for both from the same package (`monaco-typescript`), but now their coloring is separated. Long story short, we had to include `tsWorker` somewhere, so now `tsWorker` is referenced under `typescript`, even though it would also be needed for `javascript`...

**Comment by nikeee** [comment]
Was this solved in this commit?
https://github.com/microsoft/monaco-editor-webpack-plugin/commit/f86321e0521832cfd22f03fa3c6f5eacc8546b1c#diff-168726dbe96b3ce427e7fedce31bb0bcR81-R89

**Comment by alexdima** [comment]
Yes, I believe this has been resolved in the meantime.
