### ISSUE TITLE
Monaco editor webpack find shortcut is CTRL+F on MacOS

### ISSUE THREAD

**Issue by JavaCS3** [Microsoft/monaco-editor-webpack-plugin#28]
Environment
```
"monaco-editor": "^0.14.2",
"monaco-editor-webpack-plugin": "^1.5.1"
```
<img width="629" alt="2018-08-16 1 24 57" src="https://user-images.githubusercontent.com/4168698/44190153-e28e3f80-a157-11e8-9417-8487ff475dad.png">

**Comment by JavaCS3** [comment]
I use VUE CLI 3, the generated webpack.config.js is as follow. Seems webpack used a mock process object.
```javascript
{
 // ...
  node: {
    setImmediate: false,
    process: 'mock',
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }
  // ...
}
```
I can workaround it by
```javascript
// vue.config.js
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')
const webpack = require('webpack')

module.exports = {
  configureWebpack: {
    plugins: [
      new MonacoWebpackPlugin(),
      new webpack.DefinePlugin({
        'process.platform': 0 // bypass process check
      })
    ]
  }
}
```
But I think it would be better to fix that in monaco-edior to make it robuster

**Comment by alexandrudima** [comment]
Those checks are pretty robust, they can detect anything from Electron to nodejs to browsers or to web workers, but the checks are written to use `process` among other factors... I'm not sure how to change it to be more robust. What is the recommended way in webpack to detect these 4 cases ?

**Comment by JavaCS3** [comment]
@alexandrudima I don't know. I'm not webpack expert.

**Comment by alexandrudima** [comment]
Thank you, no problem. I'm also a webpack beginner myself 😄 .

**Comment by alexandrudima** [comment]
Yes, this has been fixed on `master` and the fix will make it with the next release.

https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/17
