### ISSUE TITLE
Feature request: Exclude features

### ISSUE THREAD

**Issue by nicoabie** [Microsoft/monaco-editor-webpack-plugin#31]
Hi,

First of all thanks for this great plugin. I was testing different features combinations and it ocurred to me to provide a way of excluding default features.

Example:

`{features: ['!codelens']}`

Prefixing them with a ! will exlude that feature.

It would make no sense to include and exclude so in that case only the exclusions would be computed.
I'd make a pull request with the change if needed.

Thanks

**Comment by alexandrudima** [comment]
PR welcome

**Comment by nicoabie** [comment]
Closed by pull request #37
