### ISSUE TITLE
Failed to construct 'Worker'

### ISSUE THREAD

**Issue by ktalebian** [microsoft/monaco-editor-webpack-plugin#42]
I'm trying to add the Monaco Editor, but when I add the plugin and run webpack dev-server, I get

```
Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes.

simpleWorker.js:32 Failed to construct 'Worker': Script at 'http://localhost:3020/my-app/js/typescript.worker.js' cannot be accessed from origin 'http://www.local.app.com'

VM2033:37 Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:391)
    at webWorker.js:38
    at ShallowCancelThenPromise.CompletePromise_then [as then] (winjs.base.js:1587)
    at MonacoWebWorkerImpl._getForeignProxy (webWorker.js:37)
    at MonacoWebWorkerImpl.getProxy (webWorker.js:61)
    at WorkerManager.webpackJsonp.1711.WorkerManager._getClient (workerManager.js:53)
    at WorkerManager.webpackJsonp.1711.WorkerManager.getLanguageServiceWorker (workerManager.js:72)
    at DiagnostcsAdapter.worker [as _worker] (tsMode.js:39)
    at DiagnostcsAdapter.webpackJsonp.1712.DiagnostcsAdapter._doValidate (languageFeatures.js:144)
    at onModelAdd (languageFeatures.js:103)
    at Array.forEach (<anonymous>)
    at new DiagnostcsAdapter (languageFeatures.js:135)
    at setupMode (tsMode.js:50)
    at Object.setupJavaScript (tsMode.js:14)
    at monaco.contribution.js:154
    at Object.notifySuccess [as _notify] (winjs.base.js:1191)
```

Then if I use the Editor I get

```
FATAL - Uncaught Error: Unexpected usage
Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (http://localhost:3020/my-app/my-app.js:188462:103)
    at http://localhost:3020/my-app/my-app.js:192459:30
    at ShallowCancelThenPromise.CompletePromise_then [as then] (http://localhost:3020/my-app/my-app.js:5624:49)
    at MonacoWebWorkerImpl._getForeignProxy (http://localhost:3020/my-app/my-app.js:192458:143)
    at MonacoWebWorkerImpl.getProxy (http://localhost:3020/my-app/my-app.js:192482:21)
    at WorkerManager.webpackJsonp.1711.WorkerManager._getClient (http://localhost:3020/my-app/4.js:127:34)
    at WorkerManager.webpackJsonp.1711.WorkerManager.getLanguageServiceWorker (http://localhost:3020/my-app/4.js:146:44)
    at DiagnostcsAdapter.worker [as _worker] (http://localhost:3020/my-app/4.js:52:48)
    at DiagnostcsAdapter.webpackJsonp.1712.DiagnostcsAdapter._doValidate (http://localhost:3020/my-app/4.js:329:14)
    at onModelAdd (http://localhost:3020/my-app/4.js:288:19)
    at Array.forEach (<anonymous>)
    at new DiagnostcsAdapter (http://localhost:3020/my-app/4.js:320:35)
    at setupMode (http://localhost:3020/my-app/4.js:63:5)
    at Object.setupJavaScript (http://localhost:3020/my-app/4.js:27:24)
    at http://localhost:3020/my-app/my-app.js:69160:57
    at Object.notifySuccess [as _notify] (http://localhost:3020/my-app/my-app.js:5228:59) in:
 http://localhost:3020/my-app/my-app.js:3657 col:27
```

My webpack configuration is:
```
{  
   "entry":{  
      "my-app":[  
         "webpack-dev-server/client?http://localhost:3020",
         "webpack/hot/only-dev-server",
         "./src/ts/index.tsx"
      ]
   },
   "output":{  
      "path":"/path/to/dist/js",
      "filename":"[name].js",
      "publicPath":"http://localhost:3020/my-app/js/"
   },
   "module":{  
      "rules":[  
           // giant rules for Tyepscript, JSON, CSS, LESS, and Monaco that the plugin adds
      ]
   },
   "resolve":{  
      "extensions":[  
         ".js",
         ".jsx",
         ".json",
         ".less",
         ".css",
         ".ts",
         ".tsx",
      ],
   },
   "plugins":[  
      {  
         "definitions":{  
            "ENV_DEV":"true",
            "ENV_PROD":"false",
            "process.env.NODE_ENV":"\"development\""
         }
      },
      /* Monaco Plugin is loaded -- not showing it cause it's giant */
   ],
   "devtool":"#source-map",
   "devServer":{  
      "headers":{  
         "Access-Control-Allow-Origin":"*"
      },
      "host":"localhost",
      "port":3020,
      "publicPath":"http://localhost:3020/my-app/js/",
      "hot":true,
      "inline":true,
      "contentBase":"/path/to/base"
   }
}
```

**Comment by Drau** [comment]
This looks the same as https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/32

**Comment by electr0sheep** [comment]
It may be the same issue, but #32 was closed. Seems like this error is still occurring, at least for myself and @ktalebian. I'm not using Windows, which I think the "fix" for 32 was specific for.

**Comment by Aralhi** [comment]
@electr0sheep have you resolve it? can you help me ?

**Comment by RommelTJ** [comment]
I'm getting this same issue.

**Comment by electr0sheep** [comment]
We did not resolve it. We have monaco running in the browser, but we have found that we need to use specific versions of `monaco-editor` and `monaco-editor-webpack-plugin`. They are:

1. `monaco-editor` => 0.13.1
2. `monaco-editor-webpack-plugin` => 1.4.0

Not sure if that is helpful or not, but we never got past this particular issue.

**Comment by Domiii** [comment]
Same here.

Trying to add it through a React component in an app that is based on `create-react-app`.

Added plugin to `webpack.config.js`.

Editor shows and kinda works, but it just freezes all the time when typing.
I'm getting `Unexpected usage` all the time as well.

**Comment by xingyesh** [comment]
the same issue on mac.
```javascript
monaco-editor: '0.17.0'
monaco-editor-webpack-plugin: '1.7.0'
```

**Comment by PavelGriza** [comment]
Hi, @ktalebian 

This issue happens because web workers are not allowed to load scripts from different domains.
You can find a workaround [here](https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md).

```js
const webpack = require('webpack');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

const ASSET_PATH = 'http://localhost:3020/my-app/js/';

module.exports = {
    // ...
    output: {
        globalObject: 'self',
        publicPath: ASSET_PATH
    },
    // ...
    plugins: [
        new MonacoWebpackPlugin({ 
            languages: ['typescript', /*... */],
            features: //...
        }),
        new webpack.DefinePlugin({
            'process.env.ASSET_PATH': JSON.stringify(ASSET_PATH)
        })
    ]
};
```

Before your editor is instantiated you should provide your own definition of `window.MonacoEnvironment` with your own implementation of `getWorkerUrl` function: 

```js
// or directly window.MonacoEnvironment = {
self.MonacoEnvironment = {
    getWorkerUrl: function (moduleId, label) {
        if (label === 'typescript' || label === 'javascript') {
	    return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
	        importScripts('${process.env.ASSET_PATH}/typescript.worker.js');`
	    )}`;
        }

	return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
	    importScripts('${process.env.ASSET_PATH}/editor.worker.js');`
	)}`;
    }
}
```

The idea is to load scripts with `data:text/javascript` worker URL.
[importScripts](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) will import a script provided by `'${process.env.ASSET_PATH}/editor.worker.js'` URL into worker's global scope. In your case this URL should directly point at ''http://localhost:3020/my-app/js/editor.worker.js' and ''http://localhost:3020/my-app/js/typescript.worker.js'

**Comment by maplor** [comment]
> Hi, @ktalebian
> 
> This issue happens because web workers are not allowed to load scripts from different domains.
> You can find a workaround [here](https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md).
> 
> ```js
> const webpack = require('webpack');
> const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
> 
> const ASSET_PATH = 'http://localhost:3020/my-app/js/';
> 
> module.exports = {
>     // ...
>     output: {
>         globalObject: 'self',
>         publicPath: ASSET_PATH
>     },
>     // ...
>     plugins: [
>         new MonacoWebpackPlugin({ 
>             languages: ['typescript', /*... */],
>             features: //...
>         }),
>         new webpack.DefinePlugin({
>             'process.env.ASSET_PATH': JSON.stringify(ASSET_PATH)
>         })
>     ]
> };
> ```
> 
> Before your editor is instantiated you should provide your own definition of `window.MonacoEnvironment` with your own implementation of `getWorkerUrl` function:
> 
> ```js
> // or directly window.MonacoEnvironment = {
> self.MonacoEnvironment = {
>     getWorkerUrl: function (moduleId, label) {
>         if (label === 'typescript' || label === 'javascript') {
> 	    return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
> 	        importScripts('${process.env.ASSET_PATH}/typescript.worker.js');`
> 	    )}`;
>         }
> 
> 	return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
> 	    importScripts('${process.env.ASSET_PATH}/editor.worker.js');`
> 	)}`;
>     }
> }
> ```
> 
> The idea is to load scripts with `data:text/javascript` worker URL.
> [importScripts](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) will import a script provided by `'${process.env.ASSET_PATH}/editor.worker.js'` URL into worker's global scope. In your case this URL should directly point at ''http://localhost:3020/my-app/js/editor.worker.js' and ''http://localhost:3020/my-app/js/typescript.worker.js'

It is useful in my case, thx!
