### ISSUE TITLE
TypeScript: need module declaration for use in TypeScript webpack config

### ISSUE THREAD

**Issue by dturcotte** [Microsoft/monaco-editor-webpack-plugin#47]
We use TypeScript even for webpack configs, but unfortunately this plugin doesn't have any type definitions:

```
webpack.config.ts(3,33): error TS7016: Could not find a declaration file for module 'monaco-editor-webpack-plugin'. '/[path]/node_modules/monaco-editor-webpack-plugin/index.js' implicitly has an 'any' type.
```

Even something as simple as `declare module 'monaco-editor-webpack-plugin';` would be helpful. I could imagine you going as far as checking all options like the language list, if you were so inclined, but that wouldn't be blocking.

Any chance of getting at least the module definition in place? Thanks!

**Comment by alexandrudima** [comment]
PR welcome!

**Comment by dturcotte** [comment]
@alexandrudima let me know what you think! https://github.com/Microsoft/monaco-editor-webpack-plugin/pull/48

**Comment by dturcotte** [comment]
Works perfectly in the latest release, thanks! https://github.com/Microsoft/monaco-editor-webpack-plugin/releases/tag/v1.6.0
