### ISSUE TITLE
'.apply()' is missing from the typescript definition

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/monaco-editor-webpack-plugin#49]
File: `monaco-editor-webpack-plugin\index.d.ts`

The exported plugin type does not implement the plugin type from `@types/webpack` properly, which leads to such errors:

```
        Type 'MonacoEditorWebpackPlugin' is not assignable to type 'Plugin'.
          Property 'apply' is missing in type 'MonacoEditorWebpackPlugin'.	
```

**Comment by alexandrudima** [comment]
PR welcome

**Comment by kube** [comment]
I just opened a PR at https://github.com/Microsoft/monaco-editor-webpack-plugin/pull/51

**Comment by kube** [comment]
@alexandrudima My PR fixes compatibility of `MonacoEditorWebpackPlugin` with `Webpack.Plugin`.

Though, there's still an issue because current export is CommonJS, and type definition defines an ESModule default export:

```sh
    new MonacoEditorPlugin(),
    ^
TypeError: monaco_editor_webpack_plugin_1.default is not a constructor
```

**Comment by kube** [comment]
Just updated my PR to usage CommonJS export in definition file.

**Comment by kube** [comment]
It's still possible to set `allowSyntheticDefaultImports` in tsconfig.json.
This needs to pipe compilation of webpack.config.ts to Babel to wrap module for compatibility at runtime.

(IMHO this is a little bit too much of a setup-ception)

**Comment by kube** [comment]
@alexandrudima Could you take a look at my PR? It's not a big PR but would solve the issue with TypeScript.
