### ISSUE TITLE
IMonacoEditorWebpackPluginOpts members need to be optional

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/monaco-editor-webpack-plugin#50]
File: `monaco-editor-webpack-plugin\index.d.ts`

Members of `IMonacoEditorWebpackPluginOpts` need to be optional, and the plugin should overwrite with the defaults when not present. For example, not providing `features` should include all. The current version does not support that.

**Comment by alexandrudima** [comment]
PR welcome

**Comment by alexdima** [comment]
This is now correctly typed.
