### ISSUE TITLE
[Question]How to disable default language feature and languageservice.

### ISSUE THREAD

**Issue by Aaaaash** [Microsoft/monaco-editor-webpack-plugin#55]
This is about two requestion.

1、I want use [monaco-editor-textmate](https://github.com/NeekSandhu/monaco-editor-textmate) replace built-in monaco-editor languages features, for  better syntaxic coloring using Textmate grammars. In documentation of monaco-editor-textmate:

> To get monaco-editor-textmate working with monaco-editor, you're advised to use Webpack with monaco-editor-webpack-plugin which allows you to control which of "built-in" languages should monaco-editor use/bundle, leaving the rest. With that control you must exclude any/all languages for which you'd like to use TextMate grammars based tokenization instead.

I'm try to delete 'typescript' 'css' 'json' 'html' 'javascript' 'scss' 'less' 'handlebars' in languages array

```javascript
new MonacoWebpackPlugin({
languages: ['bat', 'coffee', 'cpp', 'csharp', 'csp', 'dockerfile', 'fsharp', 'go', 'ini', 'java', 'lua', 'markdown', 'msdax', 'mysql', 'objective', 'perl', 'pgsql', 'php', 'postiats', 'powerquery', 'powershell', 'pug', 'python', 'r', 'razor', 'redis', 'redshift', 'ruby', 'rust', 'sb', 'scheme', 'shell', 'solidity', 'sql', 'st', 'swift', 'vb', 'xml', 'yaml']
})
```

 but when i was open javascript/typescript file, i get some error :
![error](https://dn-coding-net-production-pp.codehub.cn/8d11eb3e-979c-44ea-b452-8960e72e4fc3.png)
It's look like still load default language features, maybe my understanding is wrong.

2、I successfully let TypeScript LSP work for my editor，but in some event, like `hover`, it's will render two hover tips，one contains the documentation,  another one just simple type of hint, some part is same. so i want know how to disabled default typescriptLanguageServices of tsWorker.
![lsp](https://dn-coding-net-production-pp.codehub.cn/5816267c-c0c1-453b-b989-c1cae868f16e.png)
maybe it's same requestion, i hope get some answers, thanks very much.

**Comment by alexandrudima** [comment]
I think perhaps you haven't fully removed all references to `vs/language/typescript/monaco.contribution`. Are you importing `vs/editor/editor.main`, because that one will bring in the typescript contribution that defines a web worker. You could try to import `vs/editor/editor.api`.

**Comment by Aaaaash** [comment]
> I think perhaps you haven't fully removed all references to `vs/language/typescript/monaco.contribution`. Are you importing `vs/editor/editor.main`, because that one will bring in the typescript contribution that defines a web worker. You could try to import `vs/editor/editor.api`.

Thank you for you reply，it works!
