### ISSUE TITLE
Add custom language worker

### ISSUE THREAD

**Issue by amazzalel-habib** [Microsoft/monaco-editor-webpack-plugin#61]
**Hello,**
I want to add a custom language worker, I don't want to use the existing ones for ts,js, html...,I want to create a new worker for my own language which will communicate with my language service, also I don't want to use monaco-languageclient because it uses an old version of monaco.
**### any help will be appreciated!**
**Thanks!**

**Comment by alexandrudima** [comment]
Here are some explanations:

https://github.com/Microsoft/monaco-editor/issues/1317#issuecomment-468680023

https://github.com/Microsoft/monaco-editor/issues/1326#issuecomment-468781937
