### ISSUE TITLE
Update monaco-editor-webpack-plugin to support monaco-editor 0.17.0

### ISSUE THREAD

**Issue by wilsonwang881** [microsoft/monaco-editor-webpack-plugin#66]
Hello there!

The current version of the monaco-editor-webpack-plugin supports monaco-editor of version `0.15.1`. However, the latest version of the monaco editor is `0.17.0`.

Could you please update the monaco-editor-webpack-plugin to support the latest version monaco editor?

Thank you very much!

**Comment by blackshadev** [comment]
Hi into what kind of errors did you run? 
I updated monaco-editor to version 0.17.1 and it worked fine for me.

**Comment by 7rulnik** [comment]
@blackshadev I think the main problem here is wrong peerDependencies. Some people have checks in CI for this thing.

**Comment by blackshadev** [comment]
@7rulnik , that makes sense, thanks for the explanation. 
I see two pull requests open for version bumps (one for 0.16 and one for 0,17) , but no response from someone who can make the merge happen. such a shame. 
See #67

**Comment by 7rulnik** [comment]
@alexandrudima maybe you can help with this issue?

**Comment by hyvyys** [comment]
It would be really good to make this happen, in 0.15 the editor doesn't scroll in Firefox because it uses `mousewheel` event instead of the now standard `wheel`. Bump!

**Comment by bitjson** [comment]
The latest version of `monaco-editor` is now `^0.18` – any chance the peer dependency requirement could be bumped? Currently seeing `monaco-editor-webpack-plugin@1.7.0" has incorrect peer dependency "monaco-editor@^0.15.1".` every install. 

As far as I can tell, I've had no issues with using the latest version.

**Comment by codebryo** [comment]
@bitjson if you still get errors and they block you in CI, the `resolutions` field in the `package.json` can do the trick.
When verified it's all working as you want, just add the following:

```
"resolutions": {
    "monaco-editor" : "0.18.1"
}
```

That will make `yarn check` pass and turn the error into a warning.

**Comment by alexdima** [comment]
This has been done on `master` now.
