### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jsonDefaults' of undefined

### ISSUE THREAD

**Issue by domoritz** [microsoft/monaco-editor-webpack-plugin#68]
I am maintaining the react bindings for Monaco and I'm having some issues with my demo and the latest Monaco. If I update the demo, I get an error `Uncaught TypeError: Cannot read property 'jsonDefaults' of undefined`. 

To reproduce this issue, clone https://github.com/react-monaco-editor/react-monaco-editor. 

Then run `yarn && yarn build` before going into `example`. `yarn && yarn start` will work fine but if you update `monaco-editor` to `^0.17.1` and then run `yarn && yarn start`, you will see the error. 

Do you have any suggestions for what I need to change to update Monaco? Thanks!

**Comment by PunKHS** [comment]
I have the same problem.

**Comment by jkblume** [comment]
I have this problem as also (i am on `"monaco-editor": "^0.15.6"`)

**Comment by alexdima** [comment]
With the new `0.19.0` release, the following diff is needed to get things rolling:

* `example/webpack.config.js`:
  ![image](https://user-images.githubusercontent.com/5047891/71294851-14319f00-237a-11ea-8e9b-bf008cb519a2.png)

Once that change is made, I can reproduce the issue. This works as expected and is IMHO programmer error.

From what I can tell, the file `src/editor.js` in the repository loads the `monaco` API from `node_modules/monaco-editor/esm/vs/editor/editor.api` and Monaco's JSON contribution runs from `example/node_modules/monaco-editor/esm/vs/editor/language/json/monaco.contribution.js` and adds the JSON API to the `monaco` API from `example/node_modules/monaco-editor/esm/vs/editor/editor.api`.

You can validate this assumption my making an edit to `node_modules/monaco-editor/esm/vs/editor/editor.api` to add a unique property to the API object and another edit to `example/node_modules/monaco-editor/esm/vs/editor/editor.api` and add a different unique property to that API object.

Through debugging, it becomes apparent that there is some kind of mix-up of the two distinct node modules.

So, IMHO, I believe the sample is flawed.

**Comment by domoritz** [comment]
I see. Thanks for the explanation. I'm still not sure how to fix this issue, though. If I (npm/yarn) link or use webpack to use the react-monaco-editor from the parent directory, I always get the error. I tried aliasing a few more packages but no success.

```
resolve: {
    extensions: [".js", ".json"],
    alias: {
      "react-monaco-editor": ReactMonacoEditorSrc,
      "monaco-editor": MonacoEditorSrc,
      "monaco-editor/esm/vs/editor/editor.api": MonacoEditorAPISrc
    }
  },
```

Do you have any suggestions for what I could do to fix this?

**Comment by alexdima** [comment]
I think the easiest way to avoid this issue is to have a single `package.json` in the repository. Or if there are multiple `package.json` files, then only have a single `monaco-editor` across all of them.

Then, all effort must be made to load things from there (from the single monaco-editor on disk).

Otherwise, the `example` folder can be pulled out in another repository and consume `react-monaco-editor` via `npm`, which will make it that a single `monaco-editor` exists between them.
