### ISSUE TITLE
Consider prepare script in package.json?

### ISSUE THREAD

**Issue by tjk** [microsoft/monaco-editor-webpack-plugin#88]
Now that the project is converted to typescript, installing from git source no longer works (the `out` dir is not built).

Side note: when are you planning on cutting the next release? I mostly am interested in the graphql language support which I see landed in master 2 days ago (and to see if CORS improvements allow us to delete some code).

**Comment by alexdima** [comment]
I am working on it...

**Comment by tjk** [comment]
If there's anything I can do to help (eg. test), please let me know!

**Comment by alexdima** [comment]
This is now published to npm
