### ISSUE TITLE
ERR! Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'

### ISSUE THREAD

**Issue by andyforever** [microsoft/monaco-editor-webpack-plugin#91]
```json
devDependencies: {
 "monaco-editor-webpack-plugin": "1.18.1"
}

```
![image](https://user-images.githubusercontent.com/3242791/71388995-97cae480-2635-11ea-9fd3-d7fc77fdfb2f.png)

**Comment by BrightLin** [comment]
me too!, version: ^1.7.0

**Comment by iampomelo** [comment]
> me too!, version: ^1.7.0

1.8.0 has this problem, use 1.7.0 instead

**Comment by alexdima** [comment]
`monaco-editor-webpack-plugin` at `1.8.1` can be used to load `monaco-editor` `^0.19.0`. This is expressed in the peer dependency -- https://github.com/microsoft/monaco-editor-webpack-plugin/blob/7bde413e171fb58f312add5f87bb31e5a4aded0f/package.json#L31

It cannot load older versions of the `monaco-editor`, the reason being that the editor changes its internal shape across versions. 

If you want to load older versions of the `monaco-editor`, you need to use older versions of the `monaco-editor-webpack-plugin`.
