### ISSUE TITLE
Unexpected token: name «__insane_func», expected: punc «;»

### ISSUE THREAD

**Issue by DoranYun** [microsoft/monaco-editor-webpack-plugin#93]
Unexpected token when uglify the project

![image](https://user-images.githubusercontent.com/16359169/71780205-8224ca00-2ffa-11ea-91e3-004d7b664a7b.png)

in the `node_modules/monaco-editor/esm/vs/base/common/insane/insane.js[24]`

```
let __insane_func;
```

**Comment by alexdima** [comment]
AFAIK the uglify webpack plugin is deprecated and cannot handle the latest ESM syntax. AFAIK everyone is moving to Terser.

See https://github.com/webpack-contrib/uglifyjs-webpack-plugin

For example, here is how I adopted Terser: https://github.com/microsoft/monaco-editor-samples/commit/03a2082bc2d4c1fd3e040be5dc26b636cd7071ce#diff-ee9a57c44e5fe3fe3671f95bd1d45d32
