### ISSUE TITLE
vs-dark theme wrong color

### ISSUE THREAD

**Issue by wowtrxqn** [microsoft/monaco-editor-webpack-plugin#96]
when i don't use monaco-editor-webpack-plugin,the theme vs-dark color is right 
![right](https://user-images.githubusercontent.com/24369118/72660038-1e8b9b00-3a03-11ea-8988-9abee353e3af.png)

but when i use monaco-editor-webpack-plugin , seems like wrong color 
![wrong](https://user-images.githubusercontent.com/24369118/72660049-42e77780-3a03-11ea-9836-673d4d0d00a7.png)

by the way ,i use vue-monaco

**Comment by alexdima** [comment]
@wowtrxqn I cannot reproduce. I have tried https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin , which use the Monaco Webpack Plugin and the `vs-dark` theme and it works fine for me:

![image](https://user-images.githubusercontent.com/5047891/72663911-f34f7e80-39f7-11ea-85c8-8590764eca0b.png)

**Comment by wowtrxqn** [comment]
> @wowtrxqn I cannot reproduce. I have tried https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin , which uses the Monaco Webpack Plugin and the `vs-dark` theme and it works fine for me:
> 
> ![image](https://user-images.githubusercontent.com/5047891/72663911-f34f7e80-39f7-11ea-85c8-8590764eca0b.png)

how to quote this package

**Comment by alexdima** [comment]
@wowtrxqn I'm sorry, I don't understand what you mean.

**Comment by wowtrxqn** [comment]
> @wowtrxqn I'm sorry, I don't understand what you mean.

When i quote ‘monaco-editor-webpack-plugin’ package to my project，the vs-dark theme background-color is the wrong color white，but if i remove this quote in my webpack config，the editor background color of vs-dark theme Show the correct color  black

**Comment by alexdima** [comment]
@wowtrxqn I believe you, but I cannot reproduce what you are describing. I have tried with the sample at https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin

Do you have additional information to help me reproduce?

**Comment by wowtrxqn** [comment]
> @wowtrxqn I believe you, but I cannot reproduce what you are describing. I have tried with the sample at https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin
> 
> Do you have additional information to help me reproduce?

some relational package in my project env are 
"vue": "^2.6.10"
"vue-monaco": "^1.1.0",
"monaco-editor-webpack-plugin": "^1.8.2",
"monaco-editor": "^0.19.0",

Because my project is based on vue ，i used vue-monaco ，so i gusess Is it a conflict between the vue-monaco and monaco-editor-webpack-plugin?

**Comment by alexdima** [comment]
@wowtrxqn I am sorry, but I cannot reproduce your problem with the steps you have provided. It appears there is a communication barrier which we cannot overcome and I cannot help you.

**Comment by wowtrxqn** [comment]
> @wowtrxqn I am sorry, but I cannot reproduce your problem with the steps you have provided. It appears there is a communication barrier which we cannot overcome and I cannot help you.

i reproduce this bug , see my repository 
https://github.com/wowtrxqn/vue-monaco-project-test


if add monaco-editor-webpack-plugin to vue.config.js , the bug is appeared。
please help me analyze，many thanks

**Comment by alexdima** [comment]
@wowtrxqn You are using `vue-monaco`, which is built with the `monaco-editor`. Please open your issue against `vue-monaco` at https://github.com/egoist/vue-monaco .
